### ISSUE TITLE
Building for Go

### ISSUE THREAD

**Issue by mnightingale** [animetosho/node-yencode#12]
I've been trying to compile this library for use in Go.

Go has a couple of ways of doing this, but the approach I'm trying for the best performance is compiling the node-yencode source externally and letting Go find it if it's named .syso, there is barely any documentation on the approach and the only resources I've found are:

- https://github.com/golang/go/wiki/GcToolchainTricks
- https://github.com/valpackett/go-base64-simd

I'm not very familiar with compiling C/C++, I've tried to setup a CMake configuration because it seemed like it would be easiest, the config is based on bindings.gyp and sabyenc to produce a library in what I think is the format required I'm just trying to compile for amd64 currently.

Current progress is on [mnightingale/go-yencode](https://github.com/mnightingale/go-yencode) - You'll need to adjust NODE_YENCODE_LOCATION

On my Mac (I've also tried Ubuntu, have to remove a few flags and -arch) my call to C.crc_init() is failing with the below:

```zsh
$ go run .
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: -no_pie is deprecated when targeting new OS versions
Undefined symbols for architecture x86_64:
  "crc_clmul_set_funcs(unsigned int (**)(void const*, unsigned long, unsigned int))", referenced from:
      _crc_init in 000002.o(crc.cc.o)
  "crc_clmul256_set_funcs(unsigned int (**)(void const*, unsigned long, unsigned int))", referenced from:
      _crc_init in 000002.o(crc.cc.o)
  "crcutil_interface::CRC::Create(unsigned long long, unsigned long long, unsigned long, bool, unsigned long long, unsigned long long, unsigned long, bool, void const**)", referenced from:
      _crc_init in 000002.o(crc.cc.o)
  "_do_decode", referenced from:
      __cgo_3aa36c838d8d_Cfunc_do_decode in 000001.o
     (maybe you meant: __cgo_3aa36c838d8d_Cfunc_do_decode, __do_decode_end_raw , __do_decode_raw , __do_decode )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The `_do_decode` one seems clear, the symbol doesn't exist but I'm not sure how to fix that, is it because it's "static inline"?
Also I don't think I have it's signature correct because I need to figure how to pass it a YencDecoderState.
But it's really the crc_init method I'm most stuck on at the moment.

I was hoping you could see where I'm going wrong or offer any advice.
I feel like I'm really close to this working.

**Comment by animetosho** [comment]
For your build, maybe the dependent objects aren't being included in your library. I don't believe a static library actually does any linking - it just packages up the object files into an archive, so the `target_link_libraries` directive might not be doing much.  
You can use `ar -t [library file]` command to list the contents of your .syso file - it should contain all the compiled objects (a .o file for every .cc file compiled), otherwise you'll be missing symbols during link.

The source files are separated with different options to cater for running a single binary on a variety of systems. If you're just testing and don't need to distribute the compiled binary, it'll be easier to just throw all the source files together with `-march=native` compile flag, and forget the other `-m*` flags.

If you do want to build a distributable binary, perhaps include all the source files in a single library, but change the compile options for the files specifically (try `set_source_files_properties([file] PROPERTIES COMPILE_FLAGS [flags])`).

I'm not sure how Go does it's linking with a static library, but an alternative to having it all in one library, might be to have multiple (like you have now), but explicitly link the Go code to all of them.

---

`do_decode` was meant to be called from C/C++, as it's a simple inlined wrapper around a function pointer. For a library, you'd need to make a small exported function which calls `do_decode`.

Enums are effectively labelled numbers, so you can typecast YencDecoderState to/from an int.

I had thought about making a C library out of this at some point, but never got around to it. Maybe it's time...

**Comment by mnightingale** [comment]
Thanks so much, your comments pointed me in the right direction.

It seems my biggest issue apart from as you suggested that I should be making a shared library was even the times I had CMake setup nearly correctly it was failing to link or compile.

I think it was using gcc instead of g++ or equivalent, I was getting errors like:

```
Undefined symbols for architecture x86_64:
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for crcutil_interface::CRC in interface.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for crcutil_interface::Implementation<crcutil::GenericCrc<crcutil::uint128_sse2, crcutil::uint128_sse2, unsigned long, 4>, crcutil::RollingCrc<crcutil::GenericCrc<crcutil::uint128_sse2, crcutil::uint128_sse2, unsigned long, 4> > > in interface.o
...
 ```

For now as suggested I've gone back to basics, made a Makefile in the yencode directory and called `g++` with `-march=native` and a few of the cflags, added a small wrapper to simplify init and I think so that do_decode is exported and it works!

```
Result length: 128
Decoded: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```

Have you any idea what I'd need to make CMake work?

I would like to be able to create distributable package eventually, so instead of a single package ideally I'd create libyencode_sse2_amd64.syso, etc. and it should load them as needed.

**Comment by mnightingale** [comment]
I've figured out getting cmake to generate a working -march=native library which is good enough for now.

**Comment by animetosho** [comment]
Glad you got it working!

> Have you any idea what I'd need to make CMake work?

I'll look at writing one up.

**Comment by mnightingale** [comment]
I've pushed my currently working one to https://github.com/mnightingale/go-yencode

The main things I needed were `set(CMAKE_MACOSX_RPATH OFF)` because otherwise on Mac the install_path was being prefixed with `@rpath/` and Go and then couldn't find it.

Then as with the plain Makefile I'm making a shared library and just giving it all the sources.

At some point I want to see how I can make it work for multiple platforms, I'm not sure how at this stage.
Go will find all the .syso files and I believe use their name to determine which to load, so I can have avx2_amd64.syso,  avx2_386.syso, avx2_arm.syso, etc.

I haven't tried it yet but I thought maybe I could split it and produce yencoder_avx2_arm.syso etc. with just the encoder/decoder, if that won't work I could just make a single shared library for each platform with all the sources, yencode_amd64.syso, yencode_arm.syso, etc. - I think this is probably simpler.

---

I haven't had chance to see how fast it is yet but I'm expecting great things!

**Comment by animetosho** [comment]
I knocked together a quick C library: https://github.com/animetosho/rapidyenc  
Hopefully the CMake configuration there might be of some help.

**Comment by mnightingale** [comment]
That's great thanks!
